[global]
template_dir = "templates"
address = "0.0.0.0"
port = 8000

[production]
log = "critical"
secret_key = "5ZeSKWxwNICeUpHUhRhiqDF6iUzl88BVPJpwgbLa60o="

[global.databases.sqlite_database]
url = "db/db.sqlite"

[global.auth]
admin = "admin"
password = "123456"