[global]
template_dir = "templates"
address = "0.0.0.0"
port = 8080
keep_alive = 0

[production]
log = "critical"
secret_key = "5ZeSKWxwNICeUpHUhRhiqDF6iUzl88BVPJpwgbLa60o="

[global.databases.sqlite_database]
url = "db/db.sqlite"

[global.auth]
admin = "admin"
password = "123456"

[global.qiniu]
# qiniu 外链域名 + 上传图片key = 图片链接
host = "http://domain.com"
image_bucket = "bucket_name"
db_bucket = "bucket_name"
access_key = "your_access_key"
secret_key = "your_secret_key"
